# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/**/*'
    - 'spec/factories/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

RSpec:
  Enabled: true
