blank_issues_enabled: false
contact_links:
  - name: Questions or Help
    url: https://github.com/ernest-phillips/home_inventory/discussions
    about: Please ask questions in Discussions instead of Issues.
