name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
    - name: Bundle Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Lint Ruby and ERB files
      run: |
        bundle exec rubocop
        bundle exec erb-lint app/views/**/*.erb
